### ISSUE TITLE
AnsibleUndefinedVariable

### ISSUE THREAD

**Issue by marcelwester** [mrlesmithjr/ansible-drbd#6]
Hello,

i try to install the ansible drbd role on my CentOS infrastructure of 2 Nodes.
My Setup: Fedora 28 / VirtualBox
Error Message:

>TASK` [ansible-drbd : config | Configuring DRBD] ********************************
fatal: [node0]: FAILED! => {"changed": false, "msg": "AnsibleUndefinedVariable: 'ansible.vars.hostvars.HostVarsVars object' has no attribute u'ansible_eth0'"}
fatal: [node1]: FAILED! => {"changed": false, "msg": "AnsibleUndefinedVariable: 'ansible.vars.hostvars.HostVarsVars object' has no attribute `u'ansible_eth0'"}`
>
Inventory:

> Generated by Vagrant
node1 ansible_host=127.0.0.1 ansible_port=2200 ansible_user='vagrant' ansible_ssh_private_key_file='/home/marcel/vagrant/vagrant-box-templates/Centos/7/server/.vagrant/machines/node1/virtualbox/private_key'
node0 ansible_host=127.0.0.1 ansible_port=2222 ansible_user='vagrant' ansible_ssh_private_key_file='/home/marcel/vagrant/vagrant-box-templates/Centos/7/server/.vagrant/machines/node0/virtualbox/private_key'
[test_nodes]
node0
node1>

Maybe there is a problem in "global_commong.conf.j2" section.
But i try to fix the problem and give up after 2 hours. Could you help me?

> {% for disk in drbd_disks %}
resource {{ disk['resource'] }} {
{%   for host in groups[drbd_group] %}
  on {{ hostvars[host]['inventory_hostname_short'] }} {
    device {{ disk['device'] }};
    disk {{ disk['use_partition'] }};
    address {{ hostvars[host]['ansible_' + drbd_interface]['ipv4']['address'] }}:7788;
    meta-disk internal;
  }
{%   endfor %}
}
{% endfor %}

>

**Comment by marcelwester** [comment]
My mistake :)
Sry

**Comment by mrlesmithjr** [comment]
Did you figure it out? I was just looking at this myself and it looks like the included `tests/vagrant-box-templates/` needs some work :(
