### ISSUE TITLE
Getting no such job error

### ISSUE THREAD

**Issue by jonatasvieira** [mrlesmithjr/ansible-drbd#8]
When i try to build rpm on my fedora 28, i'm getting:

+ %kernel_module_package -v 9_%kernel_version -n drbd -f filelist-redhat
/var/tmp/rpm-tmp.V4u7lI: line 53: fg: %kernel_module_package: no such job

I'm using drbd-kernel.spec to build my rpm, provided file in repository.

**Comment by mrlesmithjr** [comment]
@jonatasvieira I don't think this has been tested on Fedora. Have you had any additional luck on this?
